name: Merge
on:
  pull_request:
    types:
      - closed
    paths:
      - "website/**"
jobs:
  merged:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo '{"pr_number": "${{ steps.findPr.outputs.number }}", "creator_username": "${{ github.event.pull_request.user.login  }}" }' >> pr_creator.json
      - name: Upload artifact
        uses: actions/upload-artifacts@v3.1.0
        with:
          name: pr_creator_data
