name: Merge
on:
  pull_request:
    types:
      - closed
    paths:
      - "website/**"
jobs:
  merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p data
          echo '{"pr_number": "${{ github.event.number }}", "creator_username": "${{ github.event.pull_request.user.login  }}" }' >> ./data/pr_creator.json
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: pr_creator_data
          path: data/
